### ISSUE TITLE
hosting24

### ISSUE THREAD

**Issue by Lenkaaad** [plaintextoffenders/plaintextoffenders#1]
Hosting24 now sends a reset email instead of a plaintext password.

**Comment by aviemzur** [comment]
Hi @Lenkaaad thanks for sending this in.

Can you provide some evidence? screenshots of the password reset email would do nicely.

I tried registering to the site myself, however, there seems to be no option to do this without purchasing hosting from them.

**Comment by Lenkaaad** [comment]
Hey, 
A screenshot of the reset email: https://imgur.com/a/M3Zr18g

**Comment by aviemzur** [comment]
Hi, we don't currently accept submissions via GitHub, please use the submit form on the website: https://plaintextoffenders.com/submit
