### ISSUE TITLE
opensubtitles.org

### ISSUE THREAD

**Issue by MrKickkiller** [plaintextoffenders/plaintextoffenders#14]
![opensubtitles_net_e](https://user-images.githubusercontent.com/5099359/64730608-fd102500-d4df-11e9-8bf7-95edeb00bfc2.png)

Cleaning up old passwords and noticed this had an item in my password manager. Forgot password link and here comes a plain text poorly generated password my way.

**Comment by aviemzur** [comment]
Hi, we don't currently accept submissions via GitHub, please use the submit form on the website: https://plaintextoffenders.com/submit
