### ISSUE TITLE
Sending plain text password on signup should not be considered the same as storing plaintext

### ISSUE THREAD

**Issue by samdark** [plaintextoffenders/plaintextoffenders#15]
Examples:

- https://plaintextoffenders.com/post/13010929157/ozonru-russian-amazon-like-shop
- https://plaintextoffenders.com/post/4714566183/rzdru-ticket-sale-system-russia

These are post-signup emails. There's no indication of actually storing plaintext.

**Comment by aviemzur** [comment]
Hi,

We address this question in our FAQ:

https://plaintextoffenders.com/faq/non-devs
https://plaintextoffenders.com/faq/devs

**Comment by samdark** [comment]
Yeah, but about says

> A website **storing** a password in plain text

Actually storing password in plain text and having ability to "restore" it is not the same as sending it via fairly secure medium (email) once it was generated. The FAQ is kinda wrong as well:

> - Fine, but I still get to send users their passwords once they created them so they don’t forget them, right?
>
>- No, email is not a secure medium. It was never designed to be one.

If email is not considered a secure medium, any website that provides ability to reset password knowing email (even if the password is never sent in plain text) and not asking for two factor authentication (which should not be SMS) should be listed as well. For example, Amazon:

![image](https://user-images.githubusercontent.com/47294/69821251-2ce3e480-1214-11ea-8c29-21e6fc3c1009.png)

**Comment by aviemzur** [comment]
You're correct about the about page, we'll edit that to be in line with our FAQ.

Regarding password reset links, these are considered to be an acceptable practice if the links are limited to a certain time frame (5 minutes, 1 hour, 1 day, etc..).

If the password reset link does not have a time limit, then you are correct that it is almost as bad as sending passwords via email.

**Comment by samdark** [comment]
Why does time limit matter? Suppose email is insecure channel. I have access to your email. Why can't I go to Amazon, ask for a link reset, go to email and follow it immediately?

**Comment by aviemzur** [comment]
There are other problems with email other than having your email account taken over. It is susceptible to man-in-the-middle attacks and if the email is intercepted then the person that intercepted it would be able to reset your password whenever they want.

Regarding email accounts being taken over, if that happens you are indeed in a serious problem and should work to recover it immediately and change the password. Also, big companies like PayPal thankfully have account takeover policies to protect users in case this happens to them.

**Comment by beedell-roke** [comment]
> We address this question in our FAQ.

@aviemzur, due to [`issues/36`](https://github.com/plaintextoffenders/plaintextoffenders/issues/36#issue-4194869402), I am unable to access that FAQ. What was the consensus? I ask per at least most of the submissions that [`pull/28`](https://github.com/plaintextoffenders/plaintextoffenders/pull/28#issue-3787025021) cites.
