### ISSUE TITLE
Removal from list

### ISSUE THREAD

**Issue by ghogg373** [plaintextoffenders/plaintextoffenders#17]
Hi, 

  How do we go about getting removed from the list? In the UK, and the talk to us page isn't loading. 

Thanks in advance

**Comment by aviemzur** [comment]
Hi, thanks for reaching out.

What is the domain in question?
And can you please share what was changed?

Thanks

**Comment by ghogg373** [comment]
Hi,

  It's www.hattons.co.uk . We have moved to a 3rd party identity platform
rather than managing this ourselves.

Regards

**Comment by aviemzur** [comment]
Hi,
Updating that removed the site from the list.

**Comment by ghogg373** [comment]
Great! Thank you.

**Comment by RokeJulianLockhart** [comment]
This issue should be closed if it is resolved.
