### ISSUE TITLE
Drogisterij.net

### ISSUE THREAD

**Issue by thomasvt1** [plaintextoffenders/plaintextoffenders#4]
As seen below Drogisterij.net happily sends your password after registration.

![image](https://user-images.githubusercontent.com/2271011/42761595-44af4b08-890e-11e8-8e7b-aabe0dd9a493.png)

**Comment by aviemzur** [comment]
Hi, we don't currently accept submissions via GitHub, please use the submit form on the website: https://plaintextoffenders.com/submit
